### ISSUE TITLE
PHP Fatal error:  Call to a member function get() on a non-object

### ISSUE THREAD

**Issue by ASM87** [benjamin-vauchel/BreadCrumb#9]
I am getting this fatal error from breadcumb on line 130 of the snippet. Anyone know how to fix this? My site will only load if I remove the breadcrumb call all together.

// Home crumb tpl ?
    if ($resource->get('id') == $modx->getOption('site_start'))
    {
        $tpl = $homeCrumbTpl;
    }

**Comment by Jako** [comment]
Try the fix above.

**Comment by Jako** [comment]
Sorry. Wrong fix.

**Comment by Jako** [comment]
Sorry. Wrong fix.

**Comment by benjamin-vauchel** [comment]
Hi Thomas,
Thanks for the bug report. I take a look tonight. 
Ben

**Comment by Jako** [comment]
Should be that issue.

**Comment by benjamin-vauchel** [comment]
Thanks @Jako. Fix merged to v1.4.3-pl.
